version: "3.0"

volumes:
  pg_data:
  backend_static:
  media:
services:
  kittygram_final-db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - backend_static:/backend_static/
      - media:/media/
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - backend_static:/frontend_static/
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - backend_static:/backend_static/
      - backend_static:/frontend_static/
      - media:/media/
    ports:
      - 9000:80
