version: "3.0"

volumes:
  pg_data:
  backend_static:
  media:
services:
  kittygram_final-db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: rv369/kittygram_backend:latest
    env_file: .env
    volumes:
      - backend_static:/backend_static/
      - media:/media/
  frontend:
    env_file: .env
    image: rv369/kittygram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - backend_static:/frontend_static/
  gateway:
    image: rv369/kittygram_gateway:latest
    env_file: .env
    volumes:
      - backend_static:/backend_static/
      - backend_static:/frontend_static/
      - media:/media/
    ports:
      - 9000:80
